# Generated by Django 5.1.2 on 2025-07-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billinginfo",
            name="price",
        ),
        migrations.RemoveField(
            model_name="billinginfo",
            name="total_items",
        ),
    ]
