# Generated by Django 5.1.2 on 2025-07-09 01:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment_app", "0002_remove_billinginfo_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="billing_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="stripe_payment_app.billinginfo",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
