# Generated by Django 5.1.2 on 2025-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0003_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
