# Generated by Django 5.1.2 on 2025-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0004_taxation_product_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalPays",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Shipping", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Taxation",
        ),
    ]
