# Generated by Django 5.1.2 on 2025-07-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0005_additionalpays_delete_taxation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=100)),
                ("color_code", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_variants",
                        to="ecommerce_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_color_images/")),
                (
                    "color_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ecommerce_app.colorvariant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
