# Generated by Django 5.1.2 on 2025-07-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0006_colorvariant_colorimage_delete_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalpays",
            name="Shipping",
        ),
    ]
