# Generated by Django 5.1.2 on 2025-07-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0007_remove_additionalpays_shipping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colorvariant",
            name="color_code",
        ),
    ]
