# Generated by Django 5.1.2 on 2025-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0009_order_billing_info_order_payment_order_shipping_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartproduct",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="product",
        ),
    ]
