# Generated by Django 5.1.2 on 2025-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0010_alter_cartproduct_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.DeleteModel(
            name="CartProduct",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
